### ISSUE TITLE
Syntax Colors Update

### ISSUE THREAD

**Issue by ubergeekzone** [primer/github-syntax-theme-generator#15]
I updated some of the syntax to be more close to GitHub, Thought you may like to update your code base. Please compare and update if you wish. I did not have the builder installed just thought you could compare the compiled file and go from there easily. 

```css
@import "syntax-variables";

atom-text-editor, :host {
  background-color: @syntax-background-color;
  color: @syntax-text-color;
}

atom-text-editor .gutter, :host .gutter {
  background-color: @syntax-gutter-background-color;
  color: @syntax-gutter-text-color;
}

atom-text-editor .gutter .line-number.cursor-line, :host .gutter .line-number.cursor-line {
  background-color: @syntax-gutter-background-color-selected;
  color: @syntax-gutter-text-color-selected;
}

atom-text-editor .gutter .line-number.cursor-line-no-selection, :host .gutter .line-number.cursor-line-no-selection {
  color: @syntax-gutter-text-color-selected;
}

atom-text-editor .wrap-guide, :host .wrap-guide {
  color: @syntax-wrap-guide-color;
}

atom-text-editor .indent-guide, :host .indent-guide {
  color: @syntax-indent-guide-color;
}

atom-text-editor .invisible-character, :host .invisible-character {
  color: @syntax-invisible-character-color;
}

atom-text-editor .search-results .marker .region, :host .search-results .marker .region {
  background-color: transparent;
  border: @syntax-result-marker-color;
}

atom-text-editor .search-results .marker.current-result .region, :host .search-results .marker.current-result .region {
  border: @syntax-result-marker-color-selected;
}

atom-text-editor.is-focused .cursor, :host(.is-focused) .cursor {
  border-color: @syntax-cursor-color;
}

atom-text-editor.is-focused .selection .region, :host(.is-focused) .selection .region {
  background-color: @syntax-selection-color;
}

atom-text-editor.is-focused .line-number.cursor-line-no-selection, atom-text-editor.is-focused .line.cursor-line, :host(.is-focused) .line-number.cursor-line-no-selection, :host(.is-focused) .line.cursor-line {
  background-color: #f5f5f5;
}

.comment, .punctuation.definition.comment, .string.comment {
  color: #969896;
}

.entity.name.constant,  .variable.language {
  color: #ed6a43;
}

.variable.other.constant {
  color: #0086b3;
}

.constant {
  color: #0086b3;
}

.keyword.operator.symbole, .keyword.other.mark {
}

.entity, .entity.name {
  color: #795da3;
}

.variable.parameter.function {
  color: #333333;
}

.entity.name.tag {
  color: #63a35c;
}

.keyword {
  color: #a71d5d;
}

.storage, .storage.type {
  color: #a71d5d;
}

.storage.modifier.package, .storage.modifier.import, .storage.type.java {
  color: #333;
}

.string, .punctuation.definition.string, .string .punctuation.section.embedded .source {
  color: #183691;
}

.string.unquoted.import.ada {
}

.support {
  color: #0086b3;
}

.meta.property-name {
  color: #0086b3;
}

.variable {
  color: #333333;
}

.variable.other {
  color: #333;
}

.invalid.broken {
  font-weight: bold;
  font-style: italic;
  text-decoration: underline;
  color: #b52a1d;
}

.invalid.deprecated {
  font-weight: bold;
  font-style: italic;
  text-decoration: underline;
  color: #b52a1d;
}

.invalid.illegal {
  font-style: italic;
  text-decoration: underline;
  color: #f8f8f8;
  background-color: #b52a1d;
}

.invalid.unimplemented {
  font-weight: bold;
  font-style: italic;
  text-decoration: underline;
  color: #b52a1d;
}

.message.error {
  color: #b52a1d;
}

.string .source {
  color: #333;
}

.string .variable {
  color: #0086b3;
}

.source.regexp, .string.regexp {
  color: #183691;
}

.string.regexp.character-class, .string.regexp .constant.character.escape, .string.regexp .source.ruby.embedded, .string.regexp .string.regexp.arbitrary-repitition {
  color: #183691;
}

.string.regexp .constant.character.escape {
  font-weight: bold;
  color: #63a35c;
}

.support.constant {
  color: #0086b3;
}

.support.variable {
  color: #0086b3;
}

.meta.module-reference {
  color: #0086b3;
}

.markup.list {
  color: #693a17;
}

.markup.heading, .markup.heading .entity.name {
  font-weight: bold;
  color: #1d3e81;
}

.markup.quote {
  color: #008080;
}

.markup.italic {
  font-style: italic;
  color: #333;
}

.markup.bold {
  font-weight: bold;
  color: #333;
}

.markup.raw {
  color: #0086b3;
}

.markup.deleted, .meta.diff.header.from-file, .punctuation.definition.deleted {
  color: #bd2c00;
  background-color: #ffecec;
}

.markup.inserted, .meta.diff.header.to-file, .punctuation.definition.inserted {
  color: #55a532;
  background-color: #eaffea;
}

.markup.changed, .punctuation.definition.changed {
  color: #ef9700;
  background-color: #ffe3b4;
}

.markup.ignored, .markup.untracked {
  color: #d8d8d8;
  background-color: #808080;
}

.meta.diff.range {
  font-weight: bold;
  color: #795da3;
}

.meta.diff.header {
  color: #0086b3;
}

.meta.separator {
  font-weight: bold;
  color: #1d3e81;
}

.meta.output {
  color: #1d3e81;
}

.brackethighlighter.tag, .brackethighlighter.curly, .brackethighlighter.round, .brackethighlighter.square, .brackethighlighter.angle, .brackethighlighter.quote {
  color: #595e62;
}

.brackethighlighter.unmatched {
  color: #b52a1d;
}

.sublimelinter.mark.error {
  color: #b52a1d;
}

.sublimelinter.mark.warning {
  color: #ed6a43;
}

.sublimelinter.gutter-mark {
  color: #c0c0c0;
}

.constant.other.reference.link, .string.other.link {
  text-decoration: underline;
  color: #183691;
}
```
